apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: matdomino/games-store-db
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-db-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "3"
      volumes:
      - name: mongo-db-storage
        persistentVolumeClaim:
          claimName: mongo-db-pvc