FROM mongo

COPY dbInit.mongodb.js /setup/dbInit.mongodb.js

ENV MONGO_INITDB_DATABASE=games-store-db



## OLD - MADE FOR DOCKERCOMPOSE TO ADD DATA DO DB BY ITESELF:
# FROM mongo

# COPY dbInit.mongodb.js /docker-entrypoint-initdb.d/dbInit.mongodb.js

# ENV MONGO_INITDB_DATABASE=games-store-db

