version: '3.1'

services:

  mongo-db:
    build:
      context: ./mongo-db
      dockerfile: Dockerfile
    container_name: games-store-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: games-store-db
    volumes:
      - ./mongo-db/dbInit.mongodb.js:/docker-entrypoint-initdb.d/dbInit.mongodb.js
    networks:
      - containers-net 

  express-server:
    build:
      context: ./backend-express
      dockerfile: Dockerfile
    container_name: games-store-express
    restart: always
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DB_URL=mongodb://mongo-db:27017/games-store-db
      - SECRET_TOKEN=28c2182c2bc4ddbe90bf45c805a5b5938add271e50e283acc372ffcff2dfaa4f
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
    networks:
      - containers-net

  frontend:
    build:
      context: ./front-store-games
      dockerfile: Dockerfile
    container_name: games-store-front
    restart: always
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - express-server
    networks:
      - containers-net

networks:
  containers-net:
    driver: bridge
