version: '3.1'

services:

  mongo-db:
    build:
      context: ./mongo-db
      dockerfile: Dockerfile
    container_name: games-store-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: games-store-db
    volumes:
      - ./mongo-db/dbInit.mongodb.js:/docker-entrypoint-initdb.d/dbInit.mongodb.js
    networks:
      - containers-net 

  express-server:
    build:
      context: ./backend-express
      dockerfile: Dockerfile
    container_name: games-store-express
    restart: always
    environment:
      - DB_URL=mongodb://mongo-db:27017/games-store-db
      - SECRET_TOKEN=28c2182c2bc4ddbe90bf45c805a5b5938add271e50e283acc372ffcff2dfaa4f
    depends_on:
      - mongo-db
    networks:
      - containers-net

  frontend:
    build:
      context: ./front-store-games
      dockerfile: Dockerfile
    container_name: games-store-front
    restart: always
    depends_on:
      - express-server
    networks:
      - containers-net

  nginx-proxy:
      image: nginx:latest
      container_name: games-store-nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - express-server
        - frontend
      networks:
        - containers-net

networks:
  containers-net:
    driver: bridge
